In [5]:
import pandas as pd 
import numpy as np 
import datetime 


from CV import cross_validation as CV
from CV import combinatorial as CB

# Order 
1. X, Y generation 
2. Train(valid) / Test splitting
3. CPCV
   어차피 여기서 뒤에서 개수만큼 잘라주는 거면 데이터 포인트를 자르는 것과 다를바 없음

In [6]:
df = pd.read_csv("./data/data_input_demo.csv", index_col = [0])
df = df.set_index(['date'])

In [7]:
df.head()

,13ty_index,interty_index,lty_index,mbs_index,13cy_index,intercy_index,lcy_index,ty_index,cy_index,agg_index,real_known,cat_obs1,cat_obs2,cat_knwon1,cat_knwon2,static
date,,,,,,,,,,,,,,,,
1997-05-19,133.46,784.22,840.64,751.37,668.10,893.58,912.47,824.23,861.00,715.66,215.632652,2,2,4,3,1.0
1997-05-20,133.58,785.01,840.34,751.82,668.74,894.56,912.29,824.78,861.51,716.09,980.112727,2,1,5,4,1.0
1997-05-21,133.59,784.63,836.47,751.97,668.77,893.58,908.76,823.54,859.71,715.31,247.766286,2,1,4,4,1.0
1997-05-22,133.58,784.33,834.66,751.97,668.71,892.96,906.86,822.86,858.69,714.88,306.038065,2,1,3,4,1.0
1997-05-23,133.58,784.70,835.59,752.27,668.71,893.58,907.77,823.37,859.37,715.31,944.644883,0,2,3,3,1.0

# X, Y generation

In [8]:

def generate_xy_seq(df: pd.DataFrame, x_seq = 66, y_seq = 22):
    """
    Generate samples from
    :param df:
    :param x_seq:
    :param y_seq:
    :param scaler:
    :return:
    # x: (epoch_size, input_length, num_nodes, input_dim)
    # y: (epoch_size, output_length, num_nodes, output_dim)
    """
    num_samples, num_nodes = df.shape
    dates_arr = np.array(df.index)
    data = np.expand_dims(df.values, axis = -1) # df -> array [N, F, 1]

    x_offsets = np.arange(-x_seq+1, 1)  
    y_offsets = np.arange(1, y_seq+1)

    # feature_list = [data]

    x, y = [], []
    x_date, y_date = [],[]

    min_t = abs(min(x_offsets))
    max_t = abs(num_samples - abs(max(y_offsets)))

    for t in range(min_t, max_t):
        # value seperation
        x.append(data[t+x_offsets, ...])
        y.append(data[t+y_offsets, ...])
        # date seperation
        x_date.append(dates_arr[t+x_offsets])
        y_date.append(dates_arr[t+y_offsets])
        
    x = np.stack(x, axis = 0)
    y = np.stack(y, axis = 0)

    x_date = np.stack(x_date, axis = 0)
    y_date = np.stack(y_date, axis = 0)

    return x, y, x_date, y_date

In [9]:
x, y, x_date, y_date = generate_xy_seq(df)

In [10]:
x.shape

(6298, 66, 16, 1)

In [11]:
x_date.shape

(6298, 66)

# Splitting

In [12]:
num_samples = df.shape[0]
num_train = round(num_samples * 0.8)
# num_val = round(num_train * 0.2)
# num_train = num_train - num_val   
num_test = num_samples - (num_train)

In [13]:
TRAIN = df.iloc[:num_train]
TEST = df.iloc[num_train : ]

# CPCV
- 6C2
- purging
- embargo

In [14]:
from itertools import combinations

In [15]:
numFold = 6 
combNum = 2
folds = [i for i in range(numFold)]
val_comb = list(combinations(folds, combNum))
fold_set = [(ix[0], ix[-1] + 1) for ix in np.array_split(np.arange(TRAIN.shape[0]), 6)]

In [16]:
val_comb

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 4),
 (3, 5),
 (4, 5)]

In [17]:
fold_set

[(0, 852), (852, 1704), (1704, 2555), (2555, 3406), (3406, 4257), (4257, 5108)]

In [18]:
a = (0,2)
if 0 in a:
    print ("TRUE")

TRUE

In [41]:
comb

(4, 5)

In [19]:
cv_set = {}

# for comb in val_comb: # (0,1)

# for one combination 
comb = val_comb[0]
valid_set = {}
train_set = {}

for fold_ind, _ in enumerate(fold_set):
    
    if fold_ind in comb: 
        fold = fold_set[fold_ind]        
        
        for (st_ind, end_ind) in [fold]:
            valid = TRAIN.iloc[st_ind : end_ind]
            valid_set[fold_ind] = (valid)
    else:
        
        fold = fold_set[fold_ind]
        for st_ind, end_ind in [fold]:
            train = TRAIN.iloc[st_ind : end_ind]
            train_set[fold_ind] = (train)
                
cv_set['val'] = valid_set
cv_set['train'] = train_set

In [46]:
a = {'d':[1,2,3],'e':[2,4,5]}
a.values()

dict_values([[1, 2, 3], [2, 4, 5]])

In [45]:
cv_set['val'].values()

dict_values([            13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2010-07-08      243.85        1619.92    2334.34    1715.26     1355.03
2010-07-09      243.76        1618.02    2322.43    1715.67     1354.92
2010-07-12      243.75        1618.93    2324.04    1716.79     1355.34
2010-07-13      243.65        1615.57    2305.16    1715.58     1355.31
2010-07-14      243.92        1620.02    2327.30    1717.80     1357.27
...                ...            ...        ...        ...         ...
2013-09-04      249.76        1730.50    2699.53    1825.08     1461.70
2013-09-05      249.53        1725.60    2664.88    1815.33     1460.01
2013-09-06      249.74        1729.04    2669.89    1821.96     1461.57
2013-09-09      249.91        1732.40    2685.27    1829.28     1462.70
2013-09-10      249.77        1729.44    2662.95    1824.41     1461.85

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2010-07-08        2018.94    2346.85   1839.31   2004.47    1621.99
2010-07-09        2018.11    2341.91   1836.17   2002.79    1620.78
2010-07-12        2021.11    2346.90   1837.23   2006.10    1622.10
2010-07-13        2019.26    2339.96   1831.92   2003.22    1619.55
2010-07-14        2026.27    2361.09   1838.65   2012.98    1624.31
...                   ...        ...       ...       ...        ...
2013-09-04        2308.81    2887.18   1997.07   2335.33    1781.30
2013-09-05        2300.66    2856.10   1989.24   2322.55    1772.95
2013-09-06        2305.45    2857.42   1993.18   2326.38    1777.13
2013-09-09        2310.59    2871.70   1997.87   2333.29    1782.45
2013-09-10        2305.02    2851.57   1993.03   2324.79    1777.50

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2010-07-08  174.076054         1         1           5           3     1.0
2010-07-09   54.718890         2         0           5           4     1.0
2010-07-12  731.911612         2         2           4           4     1.0
2010-07-13  884.397304         1         1           4           5     1.0
2010-07-14   32.262079         1         2           3           4     1.0
...                ...       ...       ...         ...         ...     ...
2013-09-04  846.776049         0         2           4           4     1.0
2013-09-05   74.683679         0         2           4           3     1.0
2013-09-06  818.644819         0         0           5           5     1.0
2013-09-09   19.174647         0         0           4           4     1.0
2013-09-10  887.898352         1         2           4           3     1.0

[829 rows x 16 columns],             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2013-09-11      249.89        1732.18    2675.92    1828.66     1462.71
2013-09-12      249.92        1732.56    2682.65    1829.19     1462.98
2013-09-13      249.91        1732.83    2682.84    1830.89     1462.79
2013-09-16      250.13        1736.16    2675.34    1835.62     1464.61
2013-09-17      250.22        1737.49    2688.96    1836.06     1465.12
...                ...            ...        ...        ...         ...
2016-12-08      256.05        1829.80    3331.83    2033.95     1536.26
2016-12-09      255.91        1825.79    3292.68    2027.60     1535.53
2016-12-12      255.92        1825.80    3291.81    2027.63     1535.92
2016-12-13      255.78        1824.61    3298.99    2027.55     1535.44
2016-12-14      255.45        1819.80    3295.76    2022.61     1533.52

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2013-09-11        2309.17    2861.36   1996.89   2329.99    1781.22
2013-09-12        2310.05    2867.34   1997.83   2331.94    1782.13
2013-09-13        2310.69    2867.72   1998.12   2332.50    1782.81
2013-09-16        2316.34    2867.05   2000.93   2336.53    1786.16
2013-09-17        2318.56    2877.24   2003.40   2340.39    1788.02
...                   ...        ...       ...       ...        ...
2016-12-08        2566.90    3595.47   2149.14   2682.18    1973.80
2016-12-09        2560.81    3565.15   2141.26   2670.99    1966.65
2016-12-12        2561.16    3567.26   2141.18   2671.72    1966.78
2016-12-13        2561.21    3580.02   2140.72   2674.58    1967.23
2016-12-14        2555.18    3577.44   2135.62   2669.58    1962.83

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2013-09-11  600.344376         2         2           5           4     1.0
2013-09-12  104.635288         2         0           5           4     1.0
2013-09-13  347.423794         0         0           3           5     1.0
2013-09-16  210.872065         0         0           3           4     1.0
2013-09-17  752.838056         0         2           3           4     1.0
...                ...       ...       ...         ...         ...     ...
2016-12-08  731.418635         1         1           4           3     1.0
2016-12-09  284.649371         2         1           5           3     1.0
2016-12-12  219.416173         2         0           5           4     1.0
2016-12-13  311.959586         0         1           4           3     1.0
2016-12-14   82.538813         2         2           3           3     1.0

[851 rows x 16 columns]])

test 가 위치할 수 있는 경우
purging

1. train | test : test 에서 버리기 
   train[-1], test[0] 랑 비교 


2. test | train : embargo 좀 많이 버리기 from train 에서 

   test[-1], train[0] 랑 비교

In [20]:
purging_num = 22
embargo_num = 22

In [21]:
def purging(cv_set):
    '''
    cv_set (dict): keys (train, val), values
    '''
    val_keys = list(cv_set['val'].keys())
    train_keys = list(cv_set['train'].keys())
    # print ("val_keys ", val_keys)
    for val_k in val_keys:
        print (val_k)
        if val_k-1 in train_keys: # train | test -> test 앞 버리기 
            print (" o | x ")
            cv_set['val'][val_k] = cv_set['val'][val_k].iloc[purging_num:]
            if val_k+1 in train_keys: # test | train -> train 앞 버리기 
                print (" x | o ")
                cv_set['train'][val_k+1] = cv_set['train'][val_k+1].iloc[embargo_num : ]

        elif val_k+1 in train_keys: # test | train -> train 앞 버리기 
            print (" x | o ")
            cv_set['train'][val_k+1] = cv_set['train'][val_k+1].iloc[embargo_num : ]
            if val_k-1 in train_keys: # train | test -> test 앞 버리기 
                print (" o | x | ")
                cv_set['val'][val_k] = cv_set['val'][val_k].iloc[purging_num:]
    return cv_set

In [36]:
valid_set.keys()

dict_keys([4, 5])

In [37]:
fold

(4257, 5108)

In [38]:
fold_set

[(0, 852), (852, 1704), (1704, 2555), (2555, 3406), (3406, 4257), (4257, 5108)]

In [39]:
val_comb

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 4),
 (3, 5),
 (4, 5)]

In [40]:
fold_set

[(0, 852), (852, 1704), (1704, 2555), (2555, 3406), (3406, 4257), (4257, 5108)]

In [32]:

CPCV = []
for comb in val_comb: # (0,1)
    print (f"{comb}-----------")
    cv_set = {}

    # for one combination 
    valid_set = {}
    train_set = {}

    for fold_ind, _ in enumerate(fold_set):
    # for fold_ind in list(comb):
        # print ("fold_ind: ", fold_ind)
        if fold_ind in comb: 
            # print ("VALD")
            fold = fold_set[fold_ind]        
            # print (fold)
            for (st_ind, end_ind) in [fold]:
                valid = TRAIN.iloc[st_ind : end_ind]
                valid_set[fold_ind] = valid
        else:
            # print ("TRAIN ")
            fold = fold_set[fold_ind]
            for st_ind, end_ind in [fold]:
                # print ('st_ind: ', st_ind)
                train = TRAIN.iloc[st_ind : end_ind]
                train_set[fold_ind] = train
                    
    cv_set['val'] = valid_set
    cv_set['train'] = train_set
    # print (cv_set)
    cv_set = purging(cv_set)
    
    CPCV.append(cv_set)

(0, 1)-----------
{'val': {0:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
1997-05-19      133.46         784.22     840.64     751.37      668.10
1997-05-20      133.58         785.01     840.34     751.82      668.74
1997-05-21      133.59         784.63     836.47     751.97      668.77
1997-05-22      133.58         784.33     834.66     751.97      668.71
1997-05-23      133.58         784.70     835.59     752.27      668.71
...                ...            ...        ...        ...         ...
2000-08-16      160.03         950.72    1124.45     924.39      810.25
2000-08-17      160.08         951.02    1127.72     924.66      810.48
2000-08-18      160.16         952.13    1131.18     925.38      810.92
2000-08-21      160.22         952.41    1129.04     925.35      811.15
2000-08-22      160.31         953.07    1129.72     926.32      811.70

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
1997-05-19         893.58     912.47    824.23    861.00     715.66
1997-05-20         894.56     912.29    824.78    861.51     716.09
1997-05-21         893.58     908.76    823.54    859.71     715.31
1997-05-22         892.96     906.86    822.86    858.69     714.88
1997-05-23         893.58     907.77    823.37    859.37     715.31
...                   ...        ...       ...       ...        ...
2000-08-16        1080.00    1115.47   1026.86   1045.26     881.94
2000-08-17        1080.27    1116.19   1028.11   1045.64     882.45
2000-08-18        1081.80    1118.81   1029.99   1047.40     883.65
2000-08-21        1081.65    1115.81   1029.51   1046.48     883.38
2000-08-22        1082.44    1114.97   1030.19   1046.79     884.01

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
1997-05-19  215.632652         2         2           4           3     1.0
1997-05-20  980.112727         2         1           5           4     1.0
1997-05-21  247.766286         2         1           4           4     1.0
1997-05-22  306.038065         2         1           3           4     1.0
1997-05-23  944.644883         0         2           3           3     1.0
...                ...       ...       ...         ...         ...     ...
2000-08-16  226.026624         2         2           5           5     1.0
2000-08-17  635.443038         2         1           4           3     1.0
2000-08-18  776.453337         0         1           4           4     1.0
2000-08-21   35.149254         1         2           5           3     1.0
2000-08-22  208.485116         1         2           3           5     1.0

[852 rows x 16 columns], 1:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2000-08-23      160.45         954.75    1134.57     928.52      812.58
2000-08-24      160.53         955.27    1136.50     929.04      813.02
2000-08-25      160.55         955.43    1136.38     928.72      813.15
2000-08-28      160.56         954.74    1130.61     927.80      813.45
2000-08-29      160.51         953.89    1127.21     926.35      813.13
...                ...            ...        ...        ...         ...
2003-11-21      193.90        1205.67    1507.75    1174.57     1023.41
2003-11-24      193.69        1202.62    1496.95    1172.61     1022.13
2003-11-25      193.81        1204.16    1502.98    1175.07     1022.95
2003-11-26      193.59        1201.56    1496.30    1172.70     1021.67
2003-11-27      193.59        1201.56    1496.30    1172.70     1021.67

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2000-08-23        1085.14    1119.12   1032.91   1049.78     886.27
2000-08-24        1085.78    1120.49   1033.88   1050.59     886.99
2000-08-25        1086.21    1120.54   1033.96   1050.90     886.97
2000-08-28        1085.17    1116.08   1031.65   1048.97     885.59
2000-08-29        1084.03    1112.45   1029.97   1047.20     884.15
...                   ...        ...       ...       ...        ...
2003-11-21        1459.11    1594.77   1326.99   1430.36    1153.90
2003-11-24        1454.74    1584.96   1321.79   1424.99    1150.49
2003-11-25        1457.12    1590.05   1324.57   1427.86    1152.81
2003-11-26        1453.99    1585.39   1320.80   1424.52    1150.09
2003-11-27        1453.99    1585.39   1320.80   1424.52    1150.09

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2000-08-23   33.575711         1         2           4           5     1.0
2000-08-24  512.443063         1         2           5           5     1.0
2000-08-25  159.283896         2         0           3           3     1.0
2000-08-28  523.706450         0         2           5           3     1.0
2000-08-29    7.321231         1         0           3           4     1.0
...                ...       ...       ...         ...         ...     ...
2003-11-21  688.199348         1         0           4           3     1.0
2003-11-24  628.563981         0         1           4           4     1.0
2003-11-25   56.933194         1         2           5           4     1.0
2003-11-26  800.737518         2         0           5           3     1.0
2003-11-27  113.989244         1         0           5           3     1.0

[852 rows x 16 columns]}, 'train': {2:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2003-11-28      193.44        1198.78    1485.20    1170.07     1020.84
2003-12-01      193.24        1195.95    1478.26    1167.58     1019.72
2003-12-02      193.33        1196.79    1480.61    1168.07     1020.36
2003-12-03      193.26        1195.60    1474.99    1168.33     1020.12
2003-12-04      193.41        1197.58    1481.40    1171.03     1021.00
...                ...            ...        ...        ...         ...
2007-02-26      209.01        1307.72    1780.40    1351.78     1126.70
2007-02-27      209.58        1314.06    1800.82    1355.87     1129.91
2007-02-28      209.47        1312.50    1794.08    1354.35     1129.54
2007-03-01      209.55        1312.87    1792.54    1354.32     1129.89
2007-03-02      209.79        1315.14    1798.71    1355.30     1131.08

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2003-11-28        1450.67    1576.88   1315.73   1420.23    1146.77
2003-12-01        1447.24    1572.41   1311.72   1416.71    1143.85
2003-12-02        1448.46    1575.78   1312.99   1418.34    1144.75
2003-12-03        1447.03    1570.76   1310.59   1416.21    1143.72
2003-12-04        1449.97    1576.63   1313.81   1419.65    1146.39
...                   ...        ...       ...       ...        ...
2007-02-26        1637.15    1927.34   1471.39   1632.36    1307.01
2007-02-27        1645.57    1942.98   1480.55   1641.98    1313.21
2007-02-28        1643.20    1935.23   1478.00   1638.56    1311.09
2007-03-01        1643.39    1933.37   1478.06   1638.31    1311.06
2007-03-02        1645.98    1936.35   1481.15   1640.88    1312.77

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2003-11-28  556.931393         1         2           5           5     1.0
2003-12-01  829.017553         2         0           4           5     1.0
2003-12-02  582.892178         0         0           4           3     1.0
2003-12-03  944.486089         2         2           5           3     1.0
2003-12-04  871.511366         2         0           3           3     1.0
...                ...       ...       ...         ...         ...     ...
2007-02-26  641.290990         0         1           4           4     1.0
2007-02-27  770.337219         2         2           5           4     1.0
2007-02-28  425.250213         1         1           3           5     1.0
2007-03-01  489.053542         1         1           4           4     1.0
2007-03-02  667.931025         0         1           4           4     1.0

[851 rows x 16 columns], 3:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2007-03-05      209.86        1315.49    1799.58    1355.39     1131.63
2007-03-06      209.77        1314.81    1798.77    1356.27     1131.23
2007-03-07      209.91        1316.46    1803.63    1358.17     1132.03
2007-03-08      209.90        1316.28    1801.73    1358.60     1131.98
2007-03-09      209.53        1312.15    1787.69    1355.29     1129.99
...                ...            ...        ...        ...         ...
2010-06-01      242.72        1598.75    2256.76    1694.52     1344.82
2010-06-02      242.62        1596.64    2247.24    1695.39     1343.93
2010-06-03      242.60        1595.24    2234.06    1695.41     1344.07
2010-06-04      243.10        1605.54    2287.42    1701.92     1346.76
2010-06-07      243.05        1606.13    2285.87    1702.19     1346.82

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2007-03-05        1645.66    1933.69   1481.61   1640.08    1312.81
2007-03-06        1645.07    1933.35   1480.87   1639.56    1312.86
2007-03-07        1647.69    1938.04   1483.18   1642.51    1314.95
2007-03-08        1647.74    1937.17   1482.69   1642.37    1314.91
2007-03-09        1641.93    1922.81   1476.58   1634.98    1310.39
...                   ...        ...       ...       ...        ...
2010-06-01        1987.27    2287.42   1810.21   1968.17    1598.10
2010-06-02        1983.17    2272.16   1807.11   1961.84    1596.20
2010-06-03        1982.14    2264.84   1804.33   1959.50    1595.00
2010-06-04        1994.90    2308.00   1820.16   1978.26    1605.54
2010-06-07        1995.21    2303.80   1820.57   1977.59    1605.71

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2007-03-05   90.940939         0         1           3           4     1.0
2007-03-06  491.075076         2         1           3           4     1.0
2007-03-07  930.743887         1         0           4           5     1.0
2007-03-08  439.003092         1         0           3           3     1.0
2007-03-09   92.853032         1         1           3           4     1.0
...                ...       ...       ...         ...         ...     ...
2010-06-01  201.119150         1         0           3           4     1.0
2010-06-02  840.436482         0         2           5           4     1.0
2010-06-03  477.381107         0         0           3           4     1.0
2010-06-04  827.637480         2         2           4           4     1.0
2010-06-07  782.997820         2         0           4           5     1.0

[851 rows x 16 columns], 4:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2010-06-08      243.04        1606.85    2294.52    1703.93     1346.29
2010-06-09      243.06        1606.15    2287.13    1704.45     1345.85
2010-06-10      242.80        1599.22    2250.99    1698.65     1343.99
2010-06-11      243.08        1605.09    2283.36    1703.15     1345.81
2010-06-14      243.04        1602.39    2265.16    1702.52     1346.14
...                ...            ...        ...        ...         ...
2013-09-04      249.76        1730.50    2699.53    1825.08     1461.70
2013-09-05      249.53        1725.60    2664.88    1815.33     1460.01
2013-09-06      249.74        1729.04    2669.89    1821.96     1461.57
2013-09-09      249.91        1732.40    2685.27    1829.28     1462.70
2013-09-10      249.77        1729.44    2662.95    1824.41     1461.85

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2010-06-08        1993.65    2302.60   1822.21   1976.17    1606.53
2010-06-09        1991.54    2293.69   1820.72   1972.68    1605.69
2010-06-10        1981.08    2261.74   1810.05   1958.05    1597.65
2010-06-11        1989.51    2290.35   1819.29   1970.46    1604.42
2010-06-14        1988.01    2279.80   1814.68   1967.07    1602.25
...                   ...        ...       ...       ...        ...
2013-09-04        2308.81    2887.18   1997.07   2335.33    1781.30
2013-09-05        2300.66    2856.10   1989.24   2322.55    1772.95
2013-09-06        2305.45    2857.42   1993.18   2326.38    1777.13
2013-09-09        2310.59    2871.70   1997.87   2333.29    1782.45
2013-09-10        2305.02    2851.57   1993.03   2324.79    1777.50

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2010-06-08  450.930334         1         2           3           4     1.0
2010-06-09  985.884595         0         0           4           3     1.0
2010-06-10  419.753792         0         1           4           4     1.0
2010-06-11  638.077070         0         2           4           5     1.0
2010-06-14  994.161540         2         1           3           4     1.0
...                ...       ...       ...         ...         ...     ...
2013-09-04  846.776049         0         2           4           4     1.0
2013-09-05   74.683679         0         2           4           3     1.0
2013-09-06  818.644819         0         0           5           5     1.0
2013-09-09   19.174647         0         0           4           4     1.0
2013-09-10  887.898352         1         2           4           3     1.0

[851 rows x 16 columns], 5:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2013-09-11      249.89        1732.18    2675.92    1828.66     1462.71
2013-09-12      249.92        1732.56    2682.65    1829.19     1462.98
2013-09-13      249.91        1732.83    2682.84    1830.89     1462.79
2013-09-16      250.13        1736.16    2675.34    1835.62     1464.61
2013-09-17      250.22        1737.49    2688.96    1836.06     1465.12
...                ...            ...        ...        ...         ...
2016-12-08      256.05        1829.80    3331.83    2033.95     1536.26
2016-12-09      255.91        1825.79    3292.68    2027.60     1535.53
2016-12-12      255.92        1825.80    3291.81    2027.63     1535.92
2016-12-13      255.78        1824.61    3298.99    2027.55     1535.44
2016-12-14      255.45        1819.80    3295.76    2022.61     1533.52

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2013-09-11        2309.17    2861.36   1996.89   2329.99    1781.22
2013-09-12        2310.05    2867.34   1997.83   2331.94    1782.13
2013-09-13        2310.69    2867.72   1998.12   2332.50    1782.81
2013-09-16        2316.34    2867.05   2000.93   2336.53    1786.16
2013-09-17        2318.56    2877.24   2003.40   2340.39    1788.02
...                   ...        ...       ...       ...        ...
2016-12-08        2566.90    3595.47   2149.14   2682.18    1973.80
2016-12-09        2560.81    3565.15   2141.26   2670.99    1966.65
2016-12-12        2561.16    3567.26   2141.18   2671.72    1966.78
2016-12-13        2561.21    3580.02   2140.72   2674.58    1967.23
2016-12-14        2555.18    3577.44   2135.62   2669.58    1962.83

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
2013-09-11  600.344376         2         2           5           4     1.0
2013-09-12  104.635288         2         0           5           4     1.0
2013-09-13  347.423794         0         0           3           5     1.0
2013-09-16  210.872065         0         0           3           4     1.0
2013-09-17  752.838056         0         2           3           4     1.0
...                ...       ...       ...         ...         ...     ...
2016-12-08  731.418635         1         1           4           3     1.0
2016-12-09  284.649371         2         1           5           3     1.0
2016-12-12  219.416173         2         0           5           4     1.0
2016-12-13  311.959586         0         1           4           3     1.0
2016-12-14   82.538813         2         2           3           3     1.0

[851 rows x 16 columns]}}
0
1
 x | o
(0, 2)-----------
{'val': {0:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
1997-05-19      133.46         784.22     840.64     751.37      668.10
1997-05-20      133.58         785.01     840.34     751.82      668.74
1997-05-21      133.59         784.63     836.47     751.97      668.77
1997-05-22      133.58         784.33     834.66     751.97      668.71
1997-05-23      133.58         784.70     835.59     752.27      668.71
...                ...            ...        ...        ...         ...
2000-08-16      160.03         950.72    1124.45     924.39      810.25
2000-08-17      160.08         951.02    1127.72     924.66      810.48
2000-08-18      160.16         952.13    1131.18     925.38      810.92
2000-08-21      160.22         952.41    1129.04     925.35      811.15
2000-08-22      160.31         953.07    1129.72     926.32      811.70

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
1997-05-19         893.58     912.47    824.23    861.00     715.66
1997-05-20         894.56     912.29    824.78    861.51     716.09
1997-05-21         893.58     908.76    823.54    859.71     715.31
1997-05-22         892.96     906.86    822.86    858.69     714.88
1997-05-23         893.58     907.77    823.37    859.37     715.31
...                   ...        ...       ...       ...        ...
2000-08-16        1080.00    1115.47   1026.86   1045.26     881.94
2000-08-17        1080.27    1116.19   1028.11   1045.64     882.45
2000-08-18        1081.80    1118.81   1029.99   1047.40     883.65
2000-08-21        1081.65    1115.81   1029.51   1046.48     883.38
2000-08-22        1082.44    1114.97   1030.19   1046.79     884.01

            real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
date
1997-05-19  215.632652         2         2           4           3     1.0
1997-05-20  980.112727         2         1           5           4     1.0
1997-05-21  247.766286         2         1           4           4     1.0
1997-05-22  306.038065         2         1           3           4     1.0
1997-05-23  944.644883         0         2           3           3     1.0
...                ...       ...       ...         ...         ...     ...
2000-08-16  226.026624         2         2           5           5     1.0
2000-08-17  635.443038         2         1           4           3     1.0
2000-08-18  776.453337         0         1           4           4     1.0
2000-08-21   35.149254         1         2           5           3     1.0
2000-08-22  208.485116         1         2           3           5     1.0

[852 rows x 16 columns], 2:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
date
2003-11-28      193.44        1198.78    1485.20    1170.07     1020.84
2003-12-01      193.24        1195.95    1478.26    1167.58     1019.72
2003-12-02      193.33        1196.79    1480.61    1168.07     1020.36
2003-12-03      193.26        1195.60    1474.99    1168.33     1020.12
2003-12-04      193.41        1197.58    1481.40    1171.03     1021.00
...                ...            ...        ...        ...         ...
2007-02-26      209.01        1307.72    1780.40    1351.78     1126.70
2007-02-27      209.58        1314.06    1800.82    1355.87     1129.91
2007-02-28      209.47        1312.50    1794.08    1354.35     1129.54
2007-03-01      209.55        1312.87    1792.54    1354.32     1129.89
2007-03-02      209.79        1315.14    1798.71    1355.30     1131.08

            intercy_index  lcy_index  ty_index  cy_index  agg_index  \
date
2003-11-28        1450.67    1576.88   1315.73   1420.23    1146.77
2003-12-01        1447.24    1572.41   1311.72   1416.71    1143.85
2003-12-02        1448.46    1575.78   1312.99   1418.34    1144.75
2003-12-03        1447.03    1570.76   1310.59   1416.21    1143.72
2003-12-04        1449.97    1576.63   1313.81   1419.65    1146.39
...                   ...        ...       ...       ...        ...
2007-02-26        1637.15    1927.34   1471.39   1632.36    1307.01
2007-02-27        1645.57    1942.98   1480.55   1641.98    1313.21

In [23]:
len(CPCV)

15

In [24]:
CPCV[10]['val'].keys()

dict_keys([2, 4])

In [25]:
CPCV[0]['val'][0]

,13ty_index,interty_index,lty_index,mbs_index,13cy_index,intercy_index,lcy_index,ty_index,cy_index,agg_index,real_known,cat_obs1,cat_obs2,cat_knwon1,cat_knwon2,static
date,,,,,,,,,,,,,,,,
1997-05-19,133.46,784.22,840.64,751.37,668.10,893.58,912.47,824.23,861.00,715.66,215.632652,2,2,4,3,1.0
1997-05-20,133.58,785.01,840.34,751.82,668.74,894.56,912.29,824.78,861.51,716.09,980.112727,2,1,5,4,1.0
1997-05-21,133.59,784.63,836.47,751.97,668.77,893.58,908.76,823.54,859.71,715.31,247.766286,2,1,4,4,1.0
1997-05-22,133.58,784.33,834.66,751.97,668.71,892.96,906.86,822.86,858.69,714.88,306.038065,2,1,3,4,1.0
1997-05-23,133.58,784.70,835.59,752.27,668.71,893.58,907.77,823.37,859.37,715.31,944.644883,0,2,3,3,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000-08-16,160.03,950.72,1124.45,924.39,810.25,1080.00,1115.47,1026.86,1045.26,881.94,226.026624,2,2,5,5,1.0
2000-08-17,160.08,951.02,1127.72,924.66,810.48,1080.27,1116.19,1028.11,1045.64,882.45,635.443038,2,1,4,3,1.0
2000-08-18,160.16,952.13,1131.18,925.38,810.92,1081.80,1118.81,1029.99,1047.40,883.65,776.453337,0,1,4,4,1.0
2000-08-21,160.22,952.41,1129.04,925.35,811.15,1081.65,1115.81,1029.51,1046.48,883.38,35.149254,1,2,5,3,1.0
2000-08-22,160.31,953.07,1129.72,926.32,811.70,1082.44,1114.97,1030.19,1046.79,884.01,208.485116,1,2,3,5,1.0

In [26]:
CPCV[0]['val'][1]

,13ty_index,interty_index,lty_index,mbs_index,13cy_index,intercy_index,lcy_index,ty_index,cy_index,agg_index,real_known,cat_obs1,cat_obs2,cat_knwon1,cat_knwon2,static
date,,,,,,,,,,,,,,,,
2000-08-23,160.45,954.75,1134.57,928.52,812.58,1085.14,1119.12,1032.91,1049.78,886.27,33.575711,1,2,4,5,1.0
2000-08-24,160.53,955.27,1136.50,929.04,813.02,1085.78,1120.49,1033.88,1050.59,886.99,512.443063,1,2,5,5,1.0
2000-08-25,160.55,955.43,1136.38,928.72,813.15,1086.21,1120.54,1033.96,1050.90,886.97,159.283896,2,0,3,3,1.0
2000-08-28,160.56,954.74,1130.61,927.80,813.45,1085.17,1116.08,1031.65,1048.97,885.59,523.706450,0,2,5,3,1.0
2000-08-29,160.51,953.89,1127.21,926.35,813.13,1084.03,1112.45,1029.97,1047.20,884.15,7.321231,1,0,3,4,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003-11-21,193.90,1205.67,1507.75,1174.57,1023.41,1459.11,1594.77,1326.99,1430.36,1153.90,688.199348,1,0,4,3,1.0
2003-11-24,193.69,1202.62,1496.95,1172.61,1022.13,1454.74,1584.96,1321.79,1424.99,1150.49,628.563981,0,1,4,4,1.0
2003-11-25,193.81,1204.16,1502.98,1175.07,1022.95,1457.12,1590.05,1324.57,1427.86,1152.81,56.933194,1,2,5,4,1.0
2003-11-26,193.59,1201.56,1496.30,1172.70,1021.67,1453.99,1585.39,1320.80,1424.52,1150.09,800.737518,2,0,5,3,1.0
2003-11-27,193.59,1201.56,1496.30,1172.70,1021.67,1453.99,1585.39,1320.80,1424.52,1150.09,113.989244,1,0,5,3,1.0

In [27]:
CPCV[0]['train'][2]

,13ty_index,interty_index,lty_index,mbs_index,13cy_index,intercy_index,lcy_index,ty_index,cy_index,agg_index,real_known,cat_obs1,cat_obs2,cat_knwon1,cat_knwon2,static
date,,,,,,,,,,,,,,,,
2003-12-30,194.53,1207.15,1501.30,1181.11,1027.96,1464.05,1599.64,1326.42,1435.05,1157.38,845.028169,2,0,5,5,1.0
2003-12-31,194.57,1207.86,1502.86,1182.64,1028.29,1465.06,1600.80,1327.38,1436.06,1158.44,594.303874,1,1,5,3,1.0
2004-01-01,194.57,1207.86,1502.86,1182.64,1028.29,1465.06,1600.80,1327.38,1436.06,1158.44,65.824746,2,2,3,3,1.0
2004-01-02,194.25,1203.57,1486.59,1178.78,1026.62,1459.13,1586.13,1319.84,1428.52,1153.28,654.858079,0,0,5,3,1.0
2004-01-05,194.28,1203.42,1486.60,1179.72,1026.85,1459.37,1589.03,1319.72,1429.31,1153.80,293.528200,0,2,3,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2007-02-26,209.01,1307.72,1780.40,1351.78,1126.70,1637.15,1927.34,1471.39,1632.36,1307.01,641.290990,0,1,4,4,1.0
2007-02-27,209.58,1314.06,1800.82,1355.87,1129.91,1645.57,1942.98,1480.55,1641.98,1313.21,770.337219,2,2,5,4,1.0
2007-02-28,209.47,1312.50,1794.08,1354.35,1129.54,1643.20,1935.23,1478.00,1638.56,1311.09,425.250213,1,1,3,5,1.0
2007-03-01,209.55,1312.87,1792.54,1354.32,1129.89,1643.39,1933.37,1478.06,1638.31,1311.06,489.053542,1,1,4,4,1.0
2007-03-02,209.79,1315.14,1798.71,1355.30,1131.08,1645.98,1936.35,1481.15,1640.88,1312.77,667.931025,0,1,4,4,1.0

In [28]:
CPCV[10]['val'].keys()

dict_keys([2, 4])

In [29]:
CPCV[10]['train'].keys()

dict_keys([0, 1, 3, 5])

In [30]:
CPCV[10]['val']

{2:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
 date
 2003-12-30      194.53        1207.15    1501.30    1181.11     1027.96
 2003-12-31      194.57        1207.86    1502.86    1182.64     1028.29
 2004-01-01      194.57        1207.86    1502.86    1182.64     1028.29
 2004-01-02      194.25        1203.57    1486.59    1178.78     1026.62
 2004-01-05      194.28        1203.42    1486.60    1179.72     1026.85
 ...                ...            ...        ...        ...         ...
 2007-02-26      209.01        1307.72    1780.40    1351.78     1126.70
 2007-02-27      209.58        1314.06    1800.82    1355.87     1129.91
 2007-02-28      209.47        1312.50    1794.08    1354.35     1129.54
 2007-03-01      209.55        1312.87    1792.54    1354.32     1129.89
 2007-03-02      209.79        1315.14    1798.71    1355.30     1131.08

             intercy_index  lcy_index  ty_index  cy_index  agg_index  \
 date
 2003-12-30        1464.05    1599.64   1326.42   1435.05    1157.38
 2003-12-31        1465.06    1600.80   1327.38   1436.06    1158.44
 2004-01-01        1465.06    1600.80   1327.38   1436.06    1158.44
 2004-01-02        1459.13    1586.13   1319.84   1428.52    1153.28
 2004-01-05        1459.37    1589.03   1319.72   1429.31    1153.80
 ...                   ...        ...       ...       ...        ...
 2007-02-26        1637.15    1927.34   1471.39   1632.36    1307.01
 2007-02-27        1645.57    1942.98   1480.55   1641.98    1313.21
 2007-02-28        1643.20    1935.23   1478.00   1638.56    1311.09
 2007-03-01        1643.39    1933.37   1478.06   1638.31    1311.06
 2007-03-02        1645.98    1936.35   1481.15   1640.88    1312.77

             real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
 date
 2003-12-30  845.028169         2         0           5           5     1.0
 2003-12-31  594.303874         1         1           5           3     1.0
 2004-01-01   65.824746         2         2           3           3     1.0
 2004-01-02  654.858079         0         0           5           3     1.0
 2004-01-05  293.528200         0         2           3           5     1.0
 ...                ...       ...       ...         ...         ...     ...
 2007-02-26  641.290990         0         1           4           4     1.0
 2007-02-27  770.337219         2         2           5           4     1.0
 2007-02-28  425.250213         1         1           3           5     1.0
 2007-03-01  489.053542         1         1           4           4     1.0
 2007-03-02  667.931025         0         1           4           4     1.0

 [829 rows x 16 columns],
 4:             13ty_index  interty_index  lty_index  mbs_index  13cy_index  \
 date
 2010-07-08      243.85        1619.92    2334.34    1715.26     1355.03
 2010-07-09      243.76        1618.02    2322.43    1715.67     1354.92
 2010-07-12      243.75        1618.93    2324.04    1716.79     1355.34
 2010-07-13      243.65        1615.57    2305.16    1715.58     1355.31
 2010-07-14      243.92        1620.02    2327.30    1717.80     1357.27
 ...                ...            ...        ...        ...         ...
 2013-09-04      249.76        1730.50    2699.53    1825.08     1461.70
 2013-09-05      249.53        1725.60    2664.88    1815.33     1460.01
 2013-09-06      249.74        1729.04    2669.89    1821.96     1461.57
 2013-09-09      249.91        1732.40    2685.27    1829.28     1462.70
 2013-09-10      249.77        1729.44    2662.95    1824.41     1461.85

             intercy_index  lcy_index  ty_index  cy_index  agg_index  \
 date
 2010-07-08        2018.94    2346.85   1839.31   2004.47    1621.99
 2010-07-09        2018.11    2341.91   1836.17   2002.79    1620.78
 2010-07-12        2021.11    2346.90   1837.23   2006.10    1622.10
 2010-07-13        2019.26    2339.96   1831.92   2003.22    1619.55
 2010-07-14        2026.27    2361.09   1838.65   2012.98    1624.31
 ...                   ...        ...       ...       ...        ...
 2013-09-04        2308.81    2887.18   1997.07   2335.33    1781.30
 2013-09-05        2300.66    2856.10   1989.24   2322.55    1772.95
 2013-09-06        2305.45    2857.42   1993.18   2326.38    1777.13
 2013-09-09        2310.59    2871.70   1997.87   2333.29    1782.45
 2013-09-10        2305.02    2851.57   1993.03   2324.79    1777.50

             real_known  cat_obs1  cat_obs2  cat_knwon1  cat_knwon2  static
 date
 2010-07-08  174.076054         1         1           5           3     1.0
 2010-07-09   54.718890         2         0           5           4     1.0
 2010-07-12  731.911612         2         2           4           4     1.0
 2010-07-13  884.397304         1         1           4           5     1.0
 2010-07-14   32.262079         1         2           3           4     1.0
 ...                ...       ...       ...         ...         ...     ...
 2013-09-04  846.776049         0         2           4           4     1.0
 2013-09-05   74.683679         0         2           4           3     1.0
 2013-09-06  818.644819         0         0           5           5     1.0
 2013-09-09   19.174647         0         0           4           4     1.0
 2013-09-10  887.898352         1         2           4           3     1.0

 [829 rows x 16 columns]}

## X, Y generation

In [31]:
def purging_data(samples_info_sets: pd.Series,
                 test_times: pd.Series) -> pd.Series:
    '''
    제가 기존에 사용하던 데이터는 학습 데이터와 라벨 사이의 길이가 전부 다르고 동시에 발생하기도 합니다,
    때문에 데이터를 split할때 infomation leakage가 발생하지 않기 위해 매우 신경을 써야 했습니다.
    Train starts within test & # Train ends within test & # Train envelops test를 drop해서 사용합니다
    이후 Cross Validation을 할때도 사용되게 됩니다
    CV시에는 추가적으로 테스트 셋 뒤쪽에 embargo도 넣어줍니다

    '''
    train = samples_info_sets.copy(deep=True)
    for start_ix, end_ix in test_times.iteritems():
        df0 = train[(start_ix <= train.index) & (train.index <= end_ix)].index  # Train starts within test
        df1 = train[(start_ix <= train) & (train <= end_ix)].index  # Train ends within test
        df2 = train[(train.index <= start_ix) & (end_ix <= train)].index  # Train envelops test
        train = train.drop(df0.union(df1).union(df2))
    return train


class PurgedKFold():
    '''
    Purging 과 Embargo를 통해 K fold CV를 하면서도 information leakage를 막을 수 있습니다.
    '''

    def __init__(self,
                 n_splits: int = 3,
                 samples_info_sets: pd.Series = None,
                 pct_embargo: float = 0.):
        self.n_splits = n_splits
        self.samples_info_sets = samples_info_sets
        self.pct_embargo = pct_embargo

    def split(self,
              X: pd.DataFrame,
              y: pd.Series = None):

        if X.shape[0] != self.samples_info_sets.shape[0]:
            raise ValueError("X 와 'samples_info_sets' 의 길이가 다릅니다")

        indices: np.ndarray = np.arange(X.shape[0])
        embargo: int = int(X.shape[0] * self.pct_embargo)

        test_ranges: [(int, int)] = [(ix[0], ix[-1] + 1) for ix in np.array_split(np.arange(X.shape[0]), self.n_splits)]
        for start_ix, end_ix in test_ranges:
            test_indices = indices[start_ix:end_ix]
            if end_ix < X.shape[0]:
                end_ix += embargo
            test_times = pd.Series(index=[self.samples_info_sets[start_ix]], data=[self.samples_info_sets[end_ix-1]])
            train_times = purging_data(self.samples_info_sets, test_times)

            train_indices = []
            for train_ix in train_times.index:
                train_indices.append(self.samples_info_sets.index.get_loc(train_ix))
            yield np.array(train_indices), test_indices